### ISSUE TITLE
I want the possibility to suscribe to a question to be notified when it changes.

### ISSUE THREAD

**Issue by Zenigata** [zenika-open-source/FAQ#254] opened 2020-01-09 09:14 UTC
Whether the question or the answer changes, I want the possibility to get an email if I am subscribed to the question.

Maybe you are automatically subscribed to your own questions?

**Comment by Errorname** [comment] 2020-01-09 09:17
Thanks for this feature request.
I'm closing this one as a duplicate of #99 🙂

**Closed by Errorname** 2020-01-09 09:17 UTC
